/**
 * Verification Prompt Templates
 * Core Intellectual Engine of HalluGuard AI
 */

function buildGenerationSystemPrompt() {
  return "You are an intelligent AI assistant. Provide a clear, direct, and concise answer to the user's question. Focus on factual statements without meta-commentary.";
}

function buildVerificationSystemPrompt() {
  return `You are a rigorous, skeptical fact-checking and hallucination-detection engine.
Your task is to analyze an ANSWER generated by another AI in response to a user's QUESTION.

Rules for verification:
1. Break down the generated answer into discrete, individual factual claims or assertions.
2. For each claim, evaluate whether it is SUPPORTED, UNSUPPORTED, or FABRICATED based on:
   - The provided REFERENCE TEXT (if any is given)
   - Verified real-world factual knowledge
3. Be intensely skeptical of specific personal names, historical dates, statistics, citations, prizes, and ungrounded discoveries.
4. Categorize overall verdict strictly into one of:
   - "Supported" (all claims verified, confidence > 80)
   - "Mostly Supported" (minor caveats or omissions, confidence 65-80)
   - "Partially Supported" (contains true elements mixed with misconceptions/errors, confidence 35-64)
   - "Unsupported / Hallucinated" (significant fabrication or falsehoods, confidence < 35)
5. Provide a clear plain-language explanation and concise technical notes detailing how the decision was reached.

CRITICAL: You MUST respond ONLY with a single valid JSON object. No preamble, no markdown ticks, no postscript.

JSON Schema:
{
  "verdict": "Supported" | "Mostly Supported" | "Partially Supported" | "Unsupported / Hallucinated",
  "confidence": <integer between 0 and 100>,
  "supported_claims": ["claim 1", "claim 2"],
  "potentially_hallucinated_claims": ["claim 1", "claim 2"],
  "explanation": "<Plain language explanation for end users>",
  "technical_notes": "<Concise verification details for academic evaluation>"
}`;
}

function buildVerificationUserPrompt(question, answer, referenceText = "") {
  let prompt = `QUESTION:
${question}

GENERATED ANSWER TO VERIFY:
${answer}
`;

  if (referenceText && referenceText.trim().length > 0) {
    prompt += `
REFERENCE EVIDENCE TEXT:
${referenceText.trim()}
`;
  } else {
    prompt += `
REFERENCE EVIDENCE TEXT:
None provided. Evaluate strictly against established factual consensus.
`;
  }

  prompt += `
Perform the claim-by-claim verification and output the strict JSON result:`;

  return prompt;
}

module.exports = {
  buildGenerationSystemPrompt,
  buildVerificationSystemPrompt,
  buildVerificationUserPrompt
};
